# Generated by Django 3.2.13 on 2022-06-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='avatar'),
        ),
    ]
