# Generated by Django 3.2.13 on 2022-06-03 11:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='static/default.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
